
#
# Create an SSL certificate for pound to use
#  

# XXX FIX ME - ansible_fqdn? XXX
- name: create self-signed SSL cert for pound
  command: openssl req -new -nodes -x509 -subj "/C=US/ST=Oregon/L=Portland/O=IT/CN={{ ansible_eth1.ipv4.address }}" -days 3650 -keyout /etc/pound/server.key -out /etc/pound/server.crt -extensions v3_ca creates=/etc/pound/server.crt
  register: new_cert
  notify: restart pound

- name: verify cert file
  command: openssl x509 -in /etc/pound/server.crt -text
  when: new_cert.changed

- name: create a pem file
  command: openssl x509 -in /etc/pound/server.crt -out /etc/pound/server.pem 
  when: new_cert.changed

- name: add server.key to server.pem file
  shell: openssl rsa -in /etc/pound/server.key >> /etc/pound/server.pem
  when: new_cert.changed