---

- hosts: storage

  tasks:

  - name: stop all swift-storage node services
    command: swift-init all stop
    ignore_errors: True

  - name: cleanup image mounts
    shell: umount /srv/node/{{ disk_prefix }}{{ item }}; losetup -d /dev/loop{{ item }}; rm -f /var/tmp/{{ disk_prefix }}{{ item }}.img
    with_sequence: count=3

- hosts: proxy

  tasks:

  - name: stop swift-proxy on proxy nodes
    service: name=openstack-swift-proxy state=stopped
    when: ansible_os_family == 'RedHat'

  - name: stop swift-proxy on proxy nodes
    service: name=swift-proxy state=stopped
    when: ansible_os_family == 'Debian'

  - name: remove builder files
    command: rm -f /etc/swift/{{item}}.builder
    with_items:
    - account
    - container
    - object

- hosts:
  - storage
  - proxy

  tasks:

  - name: remove ring files
    command: rm -f /etc/swift/{{item}}.ring.gz
    with_items:
    - account
    - container
    - object
